/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ccb505c0-3b99-442d-8060-08dadc6cb5e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PmyBoPpOn",
    "aws_user_pools_web_client_id": "1l93p5lbgcev46c2iscl06vi0o",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamink_targets-local",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "DynaminkREST",
            "endpoint": "https://z89m2biopd.execute-api.us-east-1.amazonaws.com/local",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
