// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2652dd07-5743-4b62-8e3c-217428b61cf8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6hCJLCHOX",
    "aws_user_pools_web_client_id": "1olhn9h30fgu9r667b8cav8o8i",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamink_targets-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "DynaminkREST",
            "endpoint": "https://qjtwlu8q6i.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
